openapi: 3.0.3
info:
  title: Employee Request API
  description: API for microservice EmployeeRequest
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /add/{firstNumber}:
    post:
      summary: This is summary
      tags:
        - "Addition"
      description: Get the added value
      operationId: addTwoNumbers
      parameters:
        - in: path
          name: firstNumber
          description: "The first number to be added"
          required: true
          schema:
            type: integer
        - in: query
          name: secondNumber
          description: "The second number to be added"
          required: true
          schema:
            type: integer
      responses:
        200:
          description: "Success"
          content:
            application/json:
              schema:
                type: integer
#                properties:
#                  message:
#                    type: integer
        400:
          description: "Smth went wrong"
          content:
            application/json:
              schema:
                type: integer
                properties:
                  error:
                    type: string
                    example: Example